RAW_BUCKET = 'datalake-raw'
STAGE_BUCKET = 'datalake-stage'
PROCESSED_BUCKET = 'datalake-processed'
DATASET_BUCKET = 'datalake-dataset'
ARTIFACT_BUCKET = 'datalake-artifact'
OUTPUT_BUCKET = 'datalake-output'

US_STATES = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
    "UK": "London",
    "MX": "Mexico",
    "ON":"Toronto"
}

US_STATES_TO_ABBR_DICT = {'ALASKA': 'AK',
 'ALABAMA': 'AL',
 'ARKANSAS': 'AR',
 'ARIZONA': 'AZ',
 'BRITISH COLUMBIA':'BC',
 'CALIFORNIA': 'CA',
 'COLORADO': 'CO',
 'CONNECTICUT': 'CT',
 'DISTRICT OF COLUMBIA': 'DC',
 'DELAWARE': 'DE',
 'FLORIDA': 'FL',
 'GEORGIA': 'GA',
 'HAWAII': 'HI',
 "HAWAI'I":'HI',
 'IOWA': 'IA',
 'IDAHO': 'ID',
 'ILLINOIS': 'IL',
 'INDIANA': 'IN',
 'KANSAS': 'KS',
 'KENTUCKY': 'KY',
 'LOUISIANA': 'LA',
 'MASSACHUSETTS': 'MA',
 'MARYLAND': 'MD',
 'MAINE': 'ME',
 'MICHIGAN': 'MI',
 'MINNESOTA': 'MN',
 'MISSOURI': 'MO',
 'MISSISSIPPI': 'MS',
 'MONTANA': 'MT',
 'NORTH CAROLINA': 'NC',
 'NORTH DAKOTA': 'ND',
 'NEBRASKA': 'NE',
 'NEW HAMPSHIRE': 'NH',
 'NEW JERSEY': 'NJ',
 'NEW MEXICO': 'NM',
 'NEVADA': 'NV',
 'NEW YORK': 'NY',
 'OHIO': 'OH',
 'OKLAHOMA': 'OK',
 'OREGON': 'OR',
 'PENNSYLVANIA': 'PA',
 'PUERTO RICO': 'PR',
 'RHODE ISLAND': 'RI',
 'SOUTH CAROLINA': 'SC',
 'SOUTH DAKOTA': 'SD',
 'TENNESSEE': 'TN',
 'TEXAS': 'TX',
 'UTAH': 'UT',
 'VIRGINIA': 'VA',
 'VERMONT': 'VT',
 'WASHINGTON': 'WA',
 'WISCONSIN': 'WI',
 'WEST VIRGINIA': 'WV',
 'WYOMING': 'WY',
 'LONDON': 'UK',
 'MEXICO': 'MX',
 'TORONTO': 'ON'}
